---
apiVersion: v1
kind: Pod
metadata:
  name: logging-app-pod-host-log
spec:
  containers:
  - name: logging-app
    image: timberio/logging-app
    args: ["-file", "/var/log/logging-app/logging-app.log"]
    volumeMounts:
    - name: logging-app-log-dir
      mountPath: /var/log/logging-app
  volumes:
  - name: logging-app-log-dir
    hostPath:
      path: /var/log/containers
